### ISSUE TITLE
php app/console doctrine:mongodb:schmea:update 失败

### ISSUE THREAD

**Issue by foreverglory** [henter/HenterGEO#1]
你好，请问一下，为什么我在执行
php app/console doctrine:mongodb:schmea:update 失败

 [InvalidArgumentException]
 There are no commands defined in the "doctrine:mongodb:schmea" namespace.

 Did you mean one of these?
     doctrine:mongodb:schema
     doctrine:mongodb:cache
     doctrine:mongodb
     doctrine:mongodb:generate
     doctrine:mongodb:mapping

composer update 命令可以执行成功
php app/console geo:data:import 也可以执行成功

PHP 版本 5.4.19
mongoDB 版本 2.4.8

**Comment by henter** [comment]
不好意思，刚刚发现readme里面的示例命令敲错了

正确的是：
php app/console doctrine:mongodb:schema:update

谢谢你的反馈！  

## 

Henter
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
