### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by zhs077** [henter/HenterGEO#2]
你好，我用mongodb2.6.4时候在创建空间索引时候失败，我表数据结构如下：
{
  "_id" : ObjectId("53fe82fbcbbcd4295879c43b"),
  "CODE" : 1003,
  "XCODE" : 910000,
  "SNAME" : "台湾省",
  "geom" : {
    "type" : "Polygon",
    "coordinates" : [[[119.5679422031828, 23.708758434480469], [119.5679498351894, 23.709660638516951], [119.5679498286612, 23.710112688211581], [119.5681939844427, 23.71010886911759], [119.568438130551, 23.71010505882165], [119.5686822789604, 23.710108872488039], [119.5691705737389, 23.70965872885618], [119.5691705643419, 23.709208574516492], [119.56892642351571, 23.70876033637348], [119.5679422031828, 23.708758434480469]]]
  },
  "ELEV" : 0,
  "XNAME" : null,
  "ID" : 2161
}

多边形的首尾点都是一样的，使用db.native.ensureIndex({'geom.coordinates':'2dsphere'})
或者 db.native.ensureIndex({'geom.coordinates':'2dsphere'})
报错   "errmsg" : "Can't extract geo keys from object, malformed geometry?:
网上找的很多资料都无法解决，特来请教您！十分感谢。

**Comment by henter** [comment]
`coordinates`是不是多了一对`[]` ? 

改为下面的试试

```
{
"_id" : ObjectId("53fe82fbcbbcd4295879c43b"),
"CODE" : 1003,
"XCODE" : 910000,
"SNAME" : "台湾省",
"geom" : {
"type" : "Polygon",
"coordinates" : [[119.5679422031828, 23.708758434480469], [119.5679498351894, 23.709660638516951], [119.5679498286612, 23.710112688211581], [119.5681939844427, 23.71010886911759], [119.568438130551, 23.71010505882165], [119.5686822789604, 23.710108872488039], [119.5691705737389, 23.70965872885618], [119.5691705643419, 23.709208574516492], [119.56892642351571, 23.70876033637348], [119.5679422031828, 23.708758434480469]]
},
"ELEV" : 0,
"XNAME" : null,
"ID" : 2161
}
```
